// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

/// The attribute used to rank tokens.
public enum TokenRankingAttribute: String, EnumType {
  case createdAt = "createdAt"
  case lastTransaction = "lastTransaction"
  /// **Deprecated**: Use createdAt instead
  case age = "age"
  case buyCount1 = "buyCount1"
  case buyCount4 = "buyCount4"
  case buyCount12 = "buyCount12"
  case buyCount24 = "buyCount24"
  case change1 = "change1"
  case change4 = "change4"
  case change12 = "change12"
  case change24 = "change24"
  case high1 = "high1"
  case high4 = "high4"
  case high12 = "high12"
  case high24 = "high24"
  case holders = "holders"
  case liquidity = "liquidity"
  case low1 = "low1"
  case low4 = "low4"
  case low12 = "low12"
  case low24 = "low24"
  case marketCap = "marketCap"
  case priceUSD = "priceUSD"
  case sellCount1 = "sellCount1"
  case sellCount4 = "sellCount4"
  case sellCount12 = "sellCount12"
  case sellCount24 = "sellCount24"
  case trendingScore = "trendingScore"
  case trendingScore1 = "trendingScore1"
  case trendingScore4 = "trendingScore4"
  case trendingScore12 = "trendingScore12"
  case trendingScore24 = "trendingScore24"
  case txnCount1 = "txnCount1"
  case txnCount4 = "txnCount4"
  case txnCount12 = "txnCount12"
  case txnCount24 = "txnCount24"
  case uniqueBuys1 = "uniqueBuys1"
  case uniqueBuys4 = "uniqueBuys4"
  case uniqueBuys12 = "uniqueBuys12"
  case uniqueBuys24 = "uniqueBuys24"
  case uniqueSells1 = "uniqueSells1"
  case uniqueSells4 = "uniqueSells4"
  case uniqueSells12 = "uniqueSells12"
  case uniqueSells24 = "uniqueSells24"
  case uniqueTransactions1 = "uniqueTransactions1"
  case uniqueTransactions4 = "uniqueTransactions4"
  case uniqueTransactions12 = "uniqueTransactions12"
  case uniqueTransactions24 = "uniqueTransactions24"
  case volume1 = "volume1"
  case volume4 = "volume4"
  case volume12 = "volume12"
  case volume24 = "volume24"
}
