version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - '${TIMESCALE_DB_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: indexer_user
      POSTGRES_PASSWORD: ${TIMESCALE_DB_PASSWORD:-password}
      POSTGRES_DB: indexer
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U indexer_user']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timescale_data:
