/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'Float': unknown;
    'Int': unknown;
    'Int_comparison_exp': { kind: 'INPUT_OBJECT'; name: 'Int_comparison_exp'; isOneOf: false; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; }; defaultValue: null }, { name: '_is_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; }; defaultValue: null }]; };
    'String': unknown;
    'String_comparison_exp': { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; isOneOf: false; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_ilike'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: '_iregex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_is_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_like'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nilike'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: '_niregex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nlike'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nregex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_nsimilar'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_regex'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: '_similar'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'balance_offset_model': { kind: 'OBJECT'; name: 'balance_offset_model'; fields: { 'balance': { name: 'balance'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; } }; }; };
    'balance_offset_model_bool_exp_bool_exp': { kind: 'INPUT_OBJECT'; name: 'balance_offset_model_bool_exp_bool_exp'; isOneOf: false; inputFields: [{ name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'balance_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: '_not'; type: { kind: 'INPUT_OBJECT'; name: 'balance_offset_model_bool_exp_bool_exp'; ofType: null; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'balance_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: 'balance'; type: { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; ofType: null; }; defaultValue: null }]; };
    'balance_offset_model_enum_name': { name: 'balance_offset_model_enum_name'; enumValues: 'balance'; };
    'balance_offset_model_order_by': { kind: 'INPUT_OBJECT'; name: 'balance_offset_model_order_by'; isOneOf: false; inputFields: [{ name: 'balance'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'buy_token_args': { kind: 'INPUT_OBJECT'; name: 'buy_token_args'; isOneOf: false; inputFields: [{ name: 'amount_to_buy'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'token_cost'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'user_wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'cursor_ordering': { name: 'cursor_ordering'; enumValues: 'ASC' | 'DESC'; };
    'interval': unknown;
    'mutation_root': { kind: 'OBJECT'; name: 'mutation_root'; fields: { 'buy_token': { name: 'buy_token'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'delete_token_transaction': { name: 'delete_token_transaction'; type: { kind: 'OBJECT'; name: 'token_transaction_mutation_response'; ofType: null; } }; 'delete_token_transaction_by_pk': { name: 'delete_token_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'delete_wallet_transaction': { name: 'delete_wallet_transaction'; type: { kind: 'OBJECT'; name: 'wallet_transaction_mutation_response'; ofType: null; } }; 'delete_wallet_transaction_by_pk': { name: 'delete_wallet_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; } }; 'insert_token_transaction': { name: 'insert_token_transaction'; type: { kind: 'OBJECT'; name: 'token_transaction_mutation_response'; ofType: null; } }; 'insert_token_transaction_one': { name: 'insert_token_transaction_one'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'insert_wallet_transaction': { name: 'insert_wallet_transaction'; type: { kind: 'OBJECT'; name: 'wallet_transaction_mutation_response'; ofType: null; } }; 'insert_wallet_transaction_one': { name: 'insert_wallet_transaction_one'; type: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; } }; 'sell_token': { name: 'sell_token'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'update_token_transaction': { name: 'update_token_transaction'; type: { kind: 'OBJECT'; name: 'token_transaction_mutation_response'; ofType: null; } }; 'update_token_transaction_by_pk': { name: 'update_token_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'update_token_transaction_many': { name: 'update_token_transaction_many'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_mutation_response'; ofType: null; }; } }; 'update_wallet_transaction': { name: 'update_wallet_transaction'; type: { kind: 'OBJECT'; name: 'wallet_transaction_mutation_response'; ofType: null; } }; 'update_wallet_transaction_by_pk': { name: 'update_wallet_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; } }; 'update_wallet_transaction_many': { name: 'update_wallet_transaction_many'; type: { kind: 'LIST'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction_mutation_response'; ofType: null; }; } }; }; };
    'numeric': unknown;
    'numeric_comparison_exp': { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; isOneOf: false; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; }; }; defaultValue: null }, { name: '_is_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; }; }; defaultValue: null }]; };
    'order_by': { name: 'order_by'; enumValues: 'asc' | 'asc_nulls_first' | 'asc_nulls_last' | 'desc' | 'desc_nulls_first' | 'desc_nulls_last'; };
    'query_root': { kind: 'OBJECT'; name: 'query_root'; fields: { 'token_transaction': { name: 'token_transaction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; 'token_transaction_aggregate': { name: 'token_transaction_aggregate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_aggregate'; ofType: null; }; } }; 'token_transaction_by_pk': { name: 'token_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'token_transaction_offset': { name: 'token_transaction_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_offset_model'; ofType: null; }; }; }; } }; 'wallet_balance_ignore_interval': { name: 'wallet_balance_ignore_interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'balance_offset_model'; ofType: null; }; }; }; } }; 'wallet_token_balance_ignore_interval': { name: 'wallet_token_balance_ignore_interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'balance_offset_model'; ofType: null; }; }; }; } }; 'wallet_transaction': { name: 'wallet_transaction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; }; }; } }; 'wallet_transaction_aggregate': { name: 'wallet_transaction_aggregate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction_aggregate'; ofType: null; }; } }; 'wallet_transaction_by_pk': { name: 'wallet_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; } }; 'wallet_transaction_offset': { name: 'wallet_transaction_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction_offset_model'; ofType: null; }; }; }; } }; }; };
    'sell_token_args': { kind: 'INPUT_OBJECT'; name: 'sell_token_args'; isOneOf: false; inputFields: [{ name: 'amount_to_sell'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'token_cost'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'user_wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'subscription_root': { kind: 'OBJECT'; name: 'subscription_root'; fields: { 'token_transaction': { name: 'token_transaction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; 'token_transaction_aggregate': { name: 'token_transaction_aggregate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_aggregate'; ofType: null; }; } }; 'token_transaction_by_pk': { name: 'token_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; } }; 'token_transaction_offset': { name: 'token_transaction_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_offset_model'; ofType: null; }; }; }; } }; 'token_transaction_stream': { name: 'token_transaction_stream'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; 'wallet_balance_ignore_interval': { name: 'wallet_balance_ignore_interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'balance_offset_model'; ofType: null; }; }; }; } }; 'wallet_token_balance_ignore_interval': { name: 'wallet_token_balance_ignore_interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'balance_offset_model'; ofType: null; }; }; }; } }; 'wallet_transaction': { name: 'wallet_transaction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; }; }; } }; 'wallet_transaction_aggregate': { name: 'wallet_transaction_aggregate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction_aggregate'; ofType: null; }; } }; 'wallet_transaction_by_pk': { name: 'wallet_transaction_by_pk'; type: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; } }; 'wallet_transaction_offset': { name: 'wallet_transaction_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction_offset_model'; ofType: null; }; }; }; } }; 'wallet_transaction_stream': { name: 'wallet_transaction_stream'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; }; }; } }; }; };
    'timestamptz': unknown;
    'timestamptz_comparison_exp': { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; isOneOf: false; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; }; }; defaultValue: null }, { name: '_is_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; }; }; defaultValue: null }]; };
    'token_transaction': { kind: 'OBJECT'; name: 'token_transaction'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; } }; 'token': { name: 'token'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'wallet_transaction': { name: 'wallet_transaction'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; } }; 'wallet_transaction_data': { name: 'wallet_transaction_data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; } }; }; };
    'token_transaction_aggregate': { kind: 'OBJECT'; name: 'token_transaction_aggregate'; fields: { 'aggregate': { name: 'aggregate'; type: { kind: 'OBJECT'; name: 'token_transaction_aggregate_fields'; ofType: null; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; }; };
    'token_transaction_aggregate_bool_exp': { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_bool_exp'; isOneOf: false; inputFields: [{ name: 'count'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_bool_exp_count'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_aggregate_bool_exp_count': { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_bool_exp_count'; isOneOf: false; inputFields: [{ name: 'arguments'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'token_transaction_select_column'; ofType: null; }; }; }; defaultValue: null }, { name: 'distinct'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'filter'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; defaultValue: null }, { name: 'predicate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'Int_comparison_exp'; ofType: null; }; }; defaultValue: null }]; };
    'token_transaction_aggregate_fields': { kind: 'OBJECT'; name: 'token_transaction_aggregate_fields'; fields: { 'avg': { name: 'avg'; type: { kind: 'OBJECT'; name: 'token_transaction_avg_fields'; ofType: null; } }; 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'max': { name: 'max'; type: { kind: 'OBJECT'; name: 'token_transaction_max_fields'; ofType: null; } }; 'min': { name: 'min'; type: { kind: 'OBJECT'; name: 'token_transaction_min_fields'; ofType: null; } }; 'stddev': { name: 'stddev'; type: { kind: 'OBJECT'; name: 'token_transaction_stddev_fields'; ofType: null; } }; 'stddev_pop': { name: 'stddev_pop'; type: { kind: 'OBJECT'; name: 'token_transaction_stddev_pop_fields'; ofType: null; } }; 'stddev_samp': { name: 'stddev_samp'; type: { kind: 'OBJECT'; name: 'token_transaction_stddev_samp_fields'; ofType: null; } }; 'sum': { name: 'sum'; type: { kind: 'OBJECT'; name: 'token_transaction_sum_fields'; ofType: null; } }; 'var_pop': { name: 'var_pop'; type: { kind: 'OBJECT'; name: 'token_transaction_var_pop_fields'; ofType: null; } }; 'var_samp': { name: 'var_samp'; type: { kind: 'OBJECT'; name: 'token_transaction_var_samp_fields'; ofType: null; } }; 'variance': { name: 'variance'; type: { kind: 'OBJECT'; name: 'token_transaction_variance_fields'; ofType: null; } }; }; };
    'token_transaction_aggregate_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_order_by'; isOneOf: false; inputFields: [{ name: 'avg'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_avg_order_by'; ofType: null; }; defaultValue: null }, { name: 'count'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'max'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_max_order_by'; ofType: null; }; defaultValue: null }, { name: 'min'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_min_order_by'; ofType: null; }; defaultValue: null }, { name: 'stddev'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_order_by'; ofType: null; }; defaultValue: null }, { name: 'stddev_pop'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_pop_order_by'; ofType: null; }; defaultValue: null }, { name: 'stddev_samp'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_samp_order_by'; ofType: null; }; defaultValue: null }, { name: 'sum'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_sum_order_by'; ofType: null; }; defaultValue: null }, { name: 'var_pop'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_var_pop_order_by'; ofType: null; }; defaultValue: null }, { name: 'var_samp'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_var_samp_order_by'; ofType: null; }; defaultValue: null }, { name: 'variance'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_variance_order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_arr_rel_insert_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_arr_rel_insert_input'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_insert_input'; ofType: null; }; }; }; }; defaultValue: null }, { name: 'on_conflict'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_on_conflict'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_avg_fields': { kind: 'OBJECT'; name: 'token_transaction_avg_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_avg_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_avg_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_bool_exp': { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; isOneOf: false; inputFields: [{ name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: '_not'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: 'amount'; type: { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction_data'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_constraint': { name: 'token_transaction_constraint'; enumValues: 'token_transaction_pkey'; };
    'token_transaction_inc_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_inc_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_insert_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_insert_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction_data'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_obj_rel_insert_input'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_max_fields': { kind: 'OBJECT'; name: 'token_transaction_max_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; 'token': { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'wallet_transaction': { name: 'wallet_transaction'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; }; };
    'token_transaction_max_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_max_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_min_fields': { kind: 'OBJECT'; name: 'token_transaction_min_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; 'token': { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'wallet_transaction': { name: 'wallet_transaction'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; }; };
    'token_transaction_min_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_min_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_mutation_response': { kind: 'OBJECT'; name: 'token_transaction_mutation_response'; fields: { 'affected_rows': { name: 'affected_rows'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'returning': { name: 'returning'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; }; };
    'token_transaction_offset_arguments': { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_arguments'; isOneOf: false; inputFields: [{ name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'interval'; ofType: null; }; }; defaultValue: null }]; };
    'token_transaction_offset_model': { kind: 'OBJECT'; name: 'token_transaction_offset_model'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; } }; 'created_at': { name: 'created_at'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; } }; 'created_at_offset': { name: 'created_at_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; } }; 'token': { name: 'token'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'wallet': { name: 'wallet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'token_transaction_offset_model_bool_exp_bool_exp': { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_model_bool_exp_bool_exp'; isOneOf: false; inputFields: [{ name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: '_not'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: 'amount'; type: { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'created_at_offset'; type: { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_offset_model_enum_name': { name: 'token_transaction_offset_model_enum_name'; enumValues: 'amount' | 'created_at' | 'created_at_offset' | 'id' | 'token' | 'wallet'; };
    'token_transaction_offset_model_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_offset_model_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'created_at_offset'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_on_conflict': { kind: 'INPUT_OBJECT'; name: 'token_transaction_on_conflict'; isOneOf: false; inputFields: [{ name: 'constraint'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'token_transaction_constraint'; ofType: null; }; }; defaultValue: null }, { name: 'update_columns'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'token_transaction_update_column'; ofType: null; }; }; }; }; defaultValue: "[]" }, { name: 'where'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction_data'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_pk_columns_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_pk_columns_input'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; }; defaultValue: null }]; };
    'token_transaction_select_column': { name: 'token_transaction_select_column'; enumValues: 'amount' | 'id' | 'token' | 'wallet_transaction'; };
    'token_transaction_set_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_set_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_stddev_fields': { kind: 'OBJECT'; name: 'token_transaction_stddev_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_stddev_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_stddev_pop_fields': { kind: 'OBJECT'; name: 'token_transaction_stddev_pop_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_stddev_pop_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_pop_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_stddev_samp_fields': { kind: 'OBJECT'; name: 'token_transaction_stddev_samp_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_stddev_samp_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_stddev_samp_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_stream_cursor_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_stream_cursor_input'; isOneOf: false; inputFields: [{ name: 'initial_value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_stream_cursor_value_input'; ofType: null; }; }; defaultValue: null }, { name: 'ordering'; type: { kind: 'ENUM'; name: 'cursor_ordering'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_stream_cursor_value_input': { kind: 'INPUT_OBJECT'; name: 'token_transaction_stream_cursor_value_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'token'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'wallet_transaction'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_sum_fields': { kind: 'OBJECT'; name: 'token_transaction_sum_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; }; };
    'token_transaction_sum_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_sum_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_update_column': { name: 'token_transaction_update_column'; enumValues: 'amount' | 'id' | 'token' | 'wallet_transaction'; };
    'token_transaction_updates': { kind: 'INPUT_OBJECT'; name: 'token_transaction_updates'; isOneOf: false; inputFields: [{ name: '_inc'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_inc_input'; ofType: null; }; defaultValue: null }, { name: '_set'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_set_input'; ofType: null; }; defaultValue: null }, { name: 'where'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; }; defaultValue: null }]; };
    'token_transaction_var_pop_fields': { kind: 'OBJECT'; name: 'token_transaction_var_pop_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_var_pop_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_var_pop_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_var_samp_fields': { kind: 'OBJECT'; name: 'token_transaction_var_samp_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_var_samp_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_var_samp_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'token_transaction_variance_fields': { kind: 'OBJECT'; name: 'token_transaction_variance_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'token_transaction_variance_order_by': { kind: 'INPUT_OBJECT'; name: 'token_transaction_variance_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'uuid': unknown;
    'uuid_comparison_exp': { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; isOneOf: false; inputFields: [{ name: '_eq'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_gt'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_gte'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_in'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; }; }; defaultValue: null }, { name: '_is_null'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: '_lt'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_lte'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_neq'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: '_nin'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; }; }; defaultValue: null }]; };
    'wallet_balance_ignore_interval_arguments': { kind: 'INPUT_OBJECT'; name: 'wallet_balance_ignore_interval_arguments'; isOneOf: false; inputFields: [{ name: 'interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'interval'; ofType: null; }; }; defaultValue: null }, { name: 'start'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'wallet_token_balance_ignore_interval_arguments': { kind: 'INPUT_OBJECT'; name: 'wallet_token_balance_ignore_interval_arguments'; isOneOf: false; inputFields: [{ name: 'interval'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'interval'; ofType: null; }; }; defaultValue: null }, { name: 'start'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; }; defaultValue: null }, { name: 'token'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'wallet_transaction': { kind: 'OBJECT'; name: 'wallet_transaction'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; } }; 'created_at': { name: 'created_at'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; } }; 'token_transactions': { name: 'token_transactions'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction'; ofType: null; }; }; }; } }; 'token_transactions_aggregate': { name: 'token_transactions_aggregate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'token_transaction_aggregate'; ofType: null; }; } }; 'wallet': { name: 'wallet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'wallet_transaction_aggregate': { kind: 'OBJECT'; name: 'wallet_transaction_aggregate'; fields: { 'aggregate': { name: 'aggregate'; type: { kind: 'OBJECT'; name: 'wallet_transaction_aggregate_fields'; ofType: null; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; }; }; } }; }; };
    'wallet_transaction_aggregate_fields': { kind: 'OBJECT'; name: 'wallet_transaction_aggregate_fields'; fields: { 'avg': { name: 'avg'; type: { kind: 'OBJECT'; name: 'wallet_transaction_avg_fields'; ofType: null; } }; 'count': { name: 'count'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'max': { name: 'max'; type: { kind: 'OBJECT'; name: 'wallet_transaction_max_fields'; ofType: null; } }; 'min': { name: 'min'; type: { kind: 'OBJECT'; name: 'wallet_transaction_min_fields'; ofType: null; } }; 'stddev': { name: 'stddev'; type: { kind: 'OBJECT'; name: 'wallet_transaction_stddev_fields'; ofType: null; } }; 'stddev_pop': { name: 'stddev_pop'; type: { kind: 'OBJECT'; name: 'wallet_transaction_stddev_pop_fields'; ofType: null; } }; 'stddev_samp': { name: 'stddev_samp'; type: { kind: 'OBJECT'; name: 'wallet_transaction_stddev_samp_fields'; ofType: null; } }; 'sum': { name: 'sum'; type: { kind: 'OBJECT'; name: 'wallet_transaction_sum_fields'; ofType: null; } }; 'var_pop': { name: 'var_pop'; type: { kind: 'OBJECT'; name: 'wallet_transaction_var_pop_fields'; ofType: null; } }; 'var_samp': { name: 'var_samp'; type: { kind: 'OBJECT'; name: 'wallet_transaction_var_samp_fields'; ofType: null; } }; 'variance': { name: 'variance'; type: { kind: 'OBJECT'; name: 'wallet_transaction_variance_fields'; ofType: null; } }; }; };
    'wallet_transaction_avg_fields': { kind: 'OBJECT'; name: 'wallet_transaction_avg_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_bool_exp': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; isOneOf: false; inputFields: [{ name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: '_not'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: 'amount'; type: { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'token_transactions'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_bool_exp'; ofType: null; }; defaultValue: null }, { name: 'token_transactions_aggregate'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_bool_exp'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_constraint': { name: 'wallet_transaction_constraint'; enumValues: 'account_transaction_pkey'; };
    'wallet_transaction_inc_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_inc_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_insert_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_insert_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'token_transactions'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_arr_rel_insert_input'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_max_fields': { kind: 'OBJECT'; name: 'wallet_transaction_max_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; 'created_at': { name: 'created_at'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; 'wallet': { name: 'wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'wallet_transaction_min_fields': { kind: 'OBJECT'; name: 'wallet_transaction_min_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; 'created_at': { name: 'created_at'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; } }; 'wallet': { name: 'wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'wallet_transaction_mutation_response': { kind: 'OBJECT'; name: 'wallet_transaction_mutation_response'; fields: { 'affected_rows': { name: 'affected_rows'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'returning': { name: 'returning'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'wallet_transaction'; ofType: null; }; }; }; } }; }; };
    'wallet_transaction_obj_rel_insert_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_obj_rel_insert_input'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_insert_input'; ofType: null; }; }; defaultValue: null }, { name: 'on_conflict'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_on_conflict'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_offset_arguments': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_arguments'; isOneOf: false; inputFields: [{ name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'interval'; ofType: null; }; }; defaultValue: null }]; };
    'wallet_transaction_offset_model': { kind: 'OBJECT'; name: 'wallet_transaction_offset_model'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; } }; 'created_at': { name: 'created_at'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; } }; 'created_at_offset': { name: 'created_at_offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; } }; 'wallet': { name: 'wallet'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'wallet_transaction_offset_model_bool_exp_bool_exp': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_model_bool_exp_bool_exp'; isOneOf: false; inputFields: [{ name: '_and'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: '_not'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; defaultValue: null }, { name: '_or'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_model_bool_exp_bool_exp'; ofType: null; }; }; }; defaultValue: null }, { name: 'amount'; type: { kind: 'INPUT_OBJECT'; name: 'numeric_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'created_at_offset'; type: { kind: 'INPUT_OBJECT'; name: 'timestamptz_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'INPUT_OBJECT'; name: 'uuid_comparison_exp'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'INPUT_OBJECT'; name: 'String_comparison_exp'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_offset_model_enum_name': { name: 'wallet_transaction_offset_model_enum_name'; enumValues: 'amount' | 'created_at' | 'created_at_offset' | 'id' | 'wallet'; };
    'wallet_transaction_offset_model_order_by': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_offset_model_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'created_at_offset'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_on_conflict': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_on_conflict'; isOneOf: false; inputFields: [{ name: 'constraint'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'wallet_transaction_constraint'; ofType: null; }; }; defaultValue: null }, { name: 'update_columns'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'wallet_transaction_update_column'; ofType: null; }; }; }; }; defaultValue: "[]" }, { name: 'where'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_order_by': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_order_by'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }, { name: 'token_transactions_aggregate'; type: { kind: 'INPUT_OBJECT'; name: 'token_transaction_aggregate_order_by'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'ENUM'; name: 'order_by'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_pk_columns_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_pk_columns_input'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; }; defaultValue: null }]; };
    'wallet_transaction_select_column': { name: 'wallet_transaction_select_column'; enumValues: 'amount' | 'created_at' | 'id' | 'wallet'; };
    'wallet_transaction_set_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_set_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_stddev_fields': { kind: 'OBJECT'; name: 'wallet_transaction_stddev_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_stddev_pop_fields': { kind: 'OBJECT'; name: 'wallet_transaction_stddev_pop_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_stddev_samp_fields': { kind: 'OBJECT'; name: 'wallet_transaction_stddev_samp_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_stream_cursor_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_stream_cursor_input'; isOneOf: false; inputFields: [{ name: 'initial_value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_stream_cursor_value_input'; ofType: null; }; }; defaultValue: null }, { name: 'ordering'; type: { kind: 'ENUM'; name: 'cursor_ordering'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_stream_cursor_value_input': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_stream_cursor_value_input'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; }; defaultValue: null }, { name: 'created_at'; type: { kind: 'SCALAR'; name: 'timestamptz'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'uuid'; ofType: null; }; defaultValue: null }, { name: 'wallet'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'wallet_transaction_sum_fields': { kind: 'OBJECT'; name: 'wallet_transaction_sum_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'numeric'; ofType: null; } }; }; };
    'wallet_transaction_update_column': { name: 'wallet_transaction_update_column'; enumValues: 'amount' | 'created_at' | 'id' | 'wallet'; };
    'wallet_transaction_updates': { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_updates'; isOneOf: false; inputFields: [{ name: '_inc'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_inc_input'; ofType: null; }; defaultValue: null }, { name: '_set'; type: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_set_input'; ofType: null; }; defaultValue: null }, { name: 'where'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'wallet_transaction_bool_exp'; ofType: null; }; }; defaultValue: null }]; };
    'wallet_transaction_var_pop_fields': { kind: 'OBJECT'; name: 'wallet_transaction_var_pop_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_var_samp_fields': { kind: 'OBJECT'; name: 'wallet_transaction_var_samp_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
    'wallet_transaction_variance_fields': { kind: 'OBJECT'; name: 'wallet_transaction_variance_fields'; fields: { 'amount': { name: 'amount'; type: { kind: 'SCALAR'; name: 'Float'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'query_root';
  mutation: 'mutation_root';
  subscription: 'subscription_root';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}