version: "3"
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - ./output/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgrespassword@host.docker.internal:5432/postgres?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"

  timescale-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9188:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://tsdbadmin:password@host.docker.internal:5433/indexer?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"
