-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."token" add column "is_pump_token" boolean
--  null default 'false';
