[toolchain]

[features]
resolution = true
skip-lint = false

# Test Validator data
[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# Program addresses
[programs.localnet]
tub = "2a1T6Xhad5kf6VvdcebQfK6RzAxcHxiAhskRYKNzmTYw"
create-token = "6aLsHmmAB7GNbQn6czDjBMwjre5gFi8NQmtMk3SireBE"

[programs.devnet]
tub = "2a1T6Xhad5kf6VvdcebQfK6RzAxcHxiAhskRYKNzmTYw"
create-token = "6aLsHmmAB7GNbQn6czDjBMwjre5gFi8NQmtMk3SireBE"
token_metadata_program = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
