// Generated by sync-operations.ts
export const TimescaleOperations = {
  queries: [
  "batch_insert_trades",
  "insert_trade",
  "get_token_trade_history_interval",
  "get_token_trade_history_interval_candles",
  "get_top_tokens_interval_by_volume"
],
  mutations: []
} as const;

export type TimescaleQueries = typeof TimescaleOperations.queries[number];
export type TimescaleMutations = typeof TimescaleOperations.mutations[number];
