name: Dry Run Migrations and Metadata to Hasura Dev Instance

on:
  push:
    branches:
      - main
      - release/*

jobs:
  dry-run-migrations-and-metadata:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
    
      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: Apply migrations
        run: cd packages/gql && pnpm hasura migrate apply --endpoint "$HASURA_ENDPOINT" --admin-secret "$HASURA_ADMIN_SECRET" --disable-interactive --database-name default --dry-run
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}

      - name: Apply metadata
        run: cd packages/gql && pnpm hasura metadata apply --endpoint "$HASURA_ENDPOINT" --admin-secret "$HASURA_ADMIN_SECRET" --dry-run --disallow-inconsistent-metadata
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
